version: '3'

services:
  app:
    build:
      context: ../app
    container_name: app
    tty: true
    networks:
      - node-network
    volumes:
      - ../app:/app
      - /app/node_modules
    command: "dockerize -wait tcp://db:3306 -timeout 20s npm start"
    depends_on:
      - db
    
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    networks:
      - node-network
    volumes:
      - ./mysql/var:/var/lib/mysql
    command: --innodb-use-native-aio=0
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_PASSWORD=root

  nginx:
    container_name: nginx
    build:
      context: nginx
    restart: always
    networks:
      - node-network
    ports:
      - 8080:80
    depends_on:
      - app

networks: 
  node-network:
    driver: bridge  